<?php
declare(strict_types=1);require __DIR__.'/../includes/bootstrap.php';require_role('student');$page_title='Student Dashboard - SMIS';
$student=db_one('SELECT s.*,c.name class_name,se.name semester_name,se.academic_year FROM students s LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN semesters se ON se.id=s.semester_id WHERE s.user_id=:id',['id'=>current_user()['id']]);if(!$student)redirect('login.php');
$modules=db_all('SELECT m.code,m.title,m.credits FROM student_modules sm JOIN modules m ON m.id=sm.module_id WHERE sm.student_id=:id ORDER BY m.code',['id'=>$student['id']]);$grades=db_all('SELECT m.code,m.title,g.coursework,g.examination,g.final_grade,g.letter_grade FROM grades g JOIN modules m ON m.id=g.module_id WHERE g.student_id=:id ORDER BY m.code',['id'=>$student['id']]);$attendance=db_all('SELECT m.code,COUNT(a.id) records,SUM(a.status="present") present,ROUND(100*SUM(a.status="present")/NULLIF(COUNT(a.id),0),1) rate FROM student_modules sm JOIN modules m ON m.id=sm.module_id LEFT JOIN attendance a ON a.student_id=sm.student_id AND a.module_id=sm.module_id WHERE sm.student_id=:id GROUP BY m.id ORDER BY m.code',['id'=>$student['id']]);$clearance=db_one('SELECT COALESCE(fc.status,"pending") finance,COALESCE(rc.status,"pending") registration,COALESCE(ec.status,"pending") exam,COALESCE(fic.status,"pending") final FROM students s LEFT JOIN finance_clearance fc ON fc.student_id=s.id LEFT JOIN registration_clearance rc ON rc.student_id=s.id LEFT JOIN exam_clearance ec ON ec.student_id=s.id LEFT JOIN final_clearance fic ON fic.student_id=s.id WHERE s.id=:id',['id'=>$student['id']]);
include __DIR__.'/../includes/header.php';?>
<div class="page-header"><h1>Welcome, <?=e(current_user()['name'])?></h1><p><?=e($student['student_number'])?> · <?=e($student['class_name']??'Class not assigned')?></p></div>
<div class="grid grid-col-4"><div class="stat-card"><div class="stat-card-value"><?=count($modules)?></div><div class="stat-card-label">Registered Modules</div></div><div class="stat-card"><div class="stat-card-value"><?=e($student['class_name']??'—')?></div><div class="stat-card-label">Student Class</div></div><div class="stat-card"><div class="stat-card-value"><?=count($grades)?></div><div class="stat-card-label">Grades Published</div></div><div class="stat-card"><div class="stat-card-value"><?=ucfirst($clearance['final']??'pending')?></div><div class="stat-card-label">Final Clearance</div></div></div>
<div class="grid grid-col-2"><div class="card"><div class="card-header">Student profile</div><div class="card-body"><dl class="profile-list"><div><dt>Full name</dt><dd><?=e(current_user()['name'])?></dd></div><div><dt>Email</dt><dd><?=e(current_user()['email'])?></dd></div><div><dt>Class</dt><dd><?=e($student['class_name']??'Not assigned')?></dd></div><div><dt>Semester</dt><dd><?=e(trim(($student['semester_name']??'').' '.($student['academic_year']??''))?:'Not assigned')?></dd></div><div><dt>Phone</dt><dd><?=e($student['phone']??'-')?></dd></div></dl></div></div>
<div class="card"><div class="card-header">Clearance status</div><div class="card-body"><?php foreach(['registration'=>'Registration','finance'=>'Financial','exam'=>'Examination','final'=>'Final'] as $key=>$label):?><div class="clearance-row"><span><?=$label?></span><?=status_badge(in_array($clearance[$key],['approved','cleared'],true)?'approved':'pending')?></div><?php endforeach?><a class="btn btn-primary btn-block" style="margin-top:18px" href="<?=url('student/clearance-document.php')?>">Download consolidated clearance</a></div></div></div>
<div class="card"><div class="card-header">Registered modules</div><div class="card-body"><table class="table"><thead><tr><th>Code</th><th>Module</th><th>Credits</th></tr></thead><tbody><?php foreach($modules as $m):?><tr><td><strong><?=e($m['code'])?></strong></td><td><?=e($m['title'])?></td><td><?=$m['credits']?></td></tr><?php endforeach?></tbody></table></div></div>
<div class="grid grid-col-2"><div class="card"><div class="card-header">Grades</div><div class="card-body"><table class="table"><thead><tr><th>Module</th><th>CW /30</th><th>Exam /70</th><th>Final</th><th>Grade</th></tr></thead><tbody><?php foreach($grades as $g):?><tr><td><?=e($g['code'])?></td><td><?=$g['coursework']?></td><td><?=$g['examination']?></td><td><strong><?=$g['final_grade']?></strong></td><td><?=$g['letter_grade']?></td></tr><?php endforeach?></tbody></table></div></div><div class="card"><div class="card-header">Attendance records</div><div class="card-body"><table class="table"><thead><tr><th>Module</th><th>Present</th><th>Records</th><th>Rate</th></tr></thead><tbody><?php foreach($attendance as $a):?><tr><td><?=e($a['code'])?></td><td><?=$a['present']??0?></td><td><?=$a['records']?></td><td><?=($a['rate']??0)?>%</td></tr><?php endforeach?></tbody></table></div></div></div>
<?php include __DIR__.'/../includes/footer.php';?>
