<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';require_role('admin');$page_title='Clearance Verification - SMIS';
if(is_post()){enforce_csrf();$student=(int)post('student_id');$type=(string)post('type');$status=(string)post('status');$remarks=trim((string)post('remarks'));$map=['finance'=>['finance_clearance','cleared_by','cleared_at',['pending','cleared','not_cleared']],'registration'=>['registration_clearance','approved_by','approved_at',['pending','approved','rejected']],'exam'=>['exam_clearance','approved_by','approved_at',['pending','approved','rejected']],'final'=>['final_clearance','approved_by','approved_at',['pending','approved','rejected']]];if(!isset($map[$type])||!in_array($status,$map[$type][3],true))respond_error('Invalid clearance update.');[$table,$by,$at]=$map[$type];db_execute("INSERT INTO $table(student_id,status,remarks,$by,$at) VALUES(:student,:status,:remarks,:user,NOW()) ON DUPLICATE KEY UPDATE status=VALUES(status),remarks=VALUES(remarks),$by=VALUES($by),$at=NOW()",['student'=>$student,'status'=>$status,'remarks'=>$remarks,'user'=>current_user()['id']]);audit_log('verify_'.$type,'students',(string)$student);respond_success(ucfirst($type).' clearance updated.','admin/clearances.php');}
$students=db_all('SELECT s.id,s.student_number,u.name,fc.status finance_status,rc.status registration_status,ec.status exam_status,fic.status final_status FROM students s JOIN users u ON u.id=s.user_id LEFT JOIN finance_clearance fc ON fc.student_id=s.id LEFT JOIN registration_clearance rc ON rc.student_id=s.id LEFT JOIN exam_clearance ec ON ec.student_id=s.id LEFT JOIN final_clearance fic ON fic.student_id=s.id ORDER BY u.name');
include __DIR__.'/../includes/header.php';?>
<div class="page-header"><h1>Clearance Verification</h1><p>Verify departmental requirements and approve final clearance.</p></div>
<div class="card"><div class="card-body"><table class="table"><thead><tr><th>Student</th><th>Financial</th><th>Registration</th><th>Examination</th><th>Final</th><th>Update</th></tr></thead><tbody><?php foreach($students as $s):?><tr><td><strong><?=e($s['name'])?></strong><br><small><?=e($s['student_number'])?></small></td><td><?=status_badge($s['finance_status']??'pending')?></td><td><?=status_badge($s['registration_status']??'pending')?></td><td><?=status_badge($s['exam_status']??'pending')?></td><td><?=status_badge($s['final_status']??'pending')?></td><td><form method="post" class="clearance-editor"><?=csrf_field()?><input type="hidden" name="student_id" value="<?=$s['id']?>"><select class="form-control" name="type"><option value="finance">Finance</option><option value="registration">Registration</option><option value="exam">Examination</option><option value="final">Final</option></select><select class="form-control" name="status"><option value="approved">Approved</option><option value="cleared">Cleared</option><option value="pending">Pending</option><option value="rejected">Rejected</option><option value="not_cleared">Not Cleared</option></select><input class="form-control" name="remarks" placeholder="Remarks"><button class="btn btn-sm btn-primary">Save</button></form></td></tr><?php endforeach?></tbody></table></div></div>
<?php include __DIR__.'/../includes/footer.php';?>
