<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';require_role('admin');$page_title='Lecturer Assignments - SMIS';
if(is_post()){enforce_csrf();$lecturer=(int)post('lecturer_id');$class=(int)post('class_id');$module=(int)post('module_id');$semester=(int)post('semester_id');db_execute('INSERT INTO lecturer_modules(lecturer_id,module_id,class_id,semester_id) VALUES(:l,:m,:c,:s) ON DUPLICATE KEY UPDATE lecturer_id=VALUES(lecturer_id)',['l'=>$lecturer,'m'=>$module,'c'=>$class,'s'=>$semester]);audit_log('assign','lecturer_modules',db_insert_id());respond_success('Lecturer assigned to class and module.','admin/lecturers.php');}
$lecturers=db_all('SELECT l.id,l.staff_number,u.name FROM lecturers l JOIN users u ON u.id=l.user_id ORDER BY u.name');$classes=db_all('SELECT * FROM classes ORDER BY name');$modules=db_all('SELECT * FROM modules ORDER BY code');$semesters=db_all('SELECT * FROM semesters ORDER BY starts_on DESC');$assignments=db_all('SELECT lm.id,u.name lecturer,c.name class,m.code,m.title,s.name semester FROM lecturer_modules lm JOIN lecturers l ON l.id=lm.lecturer_id JOIN users u ON u.id=l.user_id JOIN classes c ON c.id=lm.class_id JOIN modules m ON m.id=lm.module_id JOIN semesters s ON s.id=lm.semester_id ORDER BY u.name,m.code');
include __DIR__.'/../includes/header.php';?>
<div class="page-header"><div><h1>Lecturer Assignments</h1><p>Connect lecturers to a class, module and semester.</p></div><a class="btn btn-primary" href="<?=url('admin/users.php?action=create')?>">Create lecturer account</a></div>
<div class="card"><div class="card-header">New assignment</div><div class="card-body"><form method="post"><?=csrf_field()?><div class="grid grid-col-4"><div class="form-group"><label>Lecturer</label><select class="form-control" name="lecturer_id"><?php foreach($lecturers as $l):?><option value="<?=$l['id']?>"><?=e($l['name'].' · '.$l['staff_number'])?></option><?php endforeach?></select></div><div class="form-group"><label>Class</label><select class="form-control" name="class_id"><?php foreach($classes as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach?></select></div><div class="form-group"><label>Module</label><select class="form-control" name="module_id"><?php foreach($modules as $m):?><option value="<?=$m['id']?>"><?=e($m['code'].' · '.$m['title'])?></option><?php endforeach?></select></div><div class="form-group"><label>Semester</label><select class="form-control" name="semester_id"><?php foreach($semesters as $s):?><option value="<?=$s['id']?>"><?=e($s['name'].' '.$s['academic_year'])?></option><?php endforeach?></select></div></div><button class="btn btn-primary">Assign lecturer</button></form></div></div>
<div class="card"><div class="card-body"><table class="table"><thead><tr><th>Lecturer</th><th>Class</th><th>Module</th><th>Semester</th><th>Loaded students</th></tr></thead><tbody><?php foreach($assignments as $a):?><tr><td><?=e($a['lecturer'])?></td><td><?=e($a['class'])?></td><td><strong><?=e($a['code'])?></strong> <?=e($a['title'])?></td><td><?=e($a['semester'])?></td><td><?=db_value('SELECT COUNT(*) FROM students s JOIN student_modules sm ON sm.student_id=s.id WHERE s.class_id=(SELECT class_id FROM lecturer_modules WHERE id=:id) AND sm.module_id=(SELECT module_id FROM lecturer_modules WHERE id=:id2)',['id'=>$a['id'],'id2'=>$a['id']])?></td></tr><?php endforeach?></tbody></table></div></div>
<?php include __DIR__.'/../includes/footer.php';?>
