<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php'; require_role('admin'); $page_title='Academic Modules - SMIS'; $errors=[];
if(is_post()){enforce_csrf();$action=(string)post('action');$id=(int)post('id');
 if($action==='save'){ $code=strtoupper(trim((string)post('code')));$title=trim((string)post('title'));$credits=(int)post('credits',3);$errors=validate_required(compact('code','title'),['code'=>'Code','title'=>'Title']);
  if(!$errors){db_execute('INSERT INTO modules(id,code,title,credits) VALUES(NULLIF(:id,0),:code,:title,:credits) ON DUPLICATE KEY UPDATE code=VALUES(code),title=VALUES(title),credits=VALUES(credits)',['id'=>$id,'code'=>$code,'title'=>$title,'credits'=>$credits]);audit_log($id?'update':'create','modules',$id?(string)$id:db_insert_id());respond_success('Module saved.','admin/modules.php');}}
 if($action==='assign_semester'){ $semester=(int)post('semester_id');$selected=array_values(array_unique(array_map('intval',(array)post('modules',[]))));if(count($selected)!==6)respond_error('Select exactly six modules.');
  db()->beginTransaction();try{db_execute('DELETE FROM semester_modules WHERE semester_id=:id',['id'=>$semester]);foreach($selected as $module)db_execute('INSERT INTO semester_modules(semester_id,module_id) VALUES(:s,:m)',['s'=>$semester,'m'=>$module]);db()->commit();audit_log('assign_modules','semesters',(string)$semester);respond_success('Six semester modules assigned.','admin/modules.php');}catch(Throwable $e){db()->rollBack();throw $e;}}
}
$editing=query('action')==='edit'?db_one('SELECT * FROM modules WHERE id=:id',['id'=>(int)query('id')]):null;$modules=db_all('SELECT * FROM modules ORDER BY code');$semesters=db_all('SELECT * FROM semesters ORDER BY starts_on DESC');
include __DIR__.'/../includes/header.php';?>
<div class="page-header"><div><h1>Academic Modules</h1><p>Create modules and assign exactly six to each semester.</p></div><a class="btn btn-primary" href="<?=url('admin/modules.php?action=create')?>">Create module</a></div>
<?php if(query('action')==='create'||$editing):?><div class="card"><div class="card-header"><?=$editing?'Edit':'Create'?> module</div><div class="card-body"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=(int)($editing['id']??0)?>"><div class="grid grid-col-3"><div class="form-group"><label>Code</label><input class="form-control" name="code" required value="<?=e($editing['code']??'')?>"></div><div class="form-group"><label>Title</label><input class="form-control" name="title" required value="<?=e($editing['title']??'')?>"></div><div class="form-group"><label>Credits</label><input class="form-control" type="number" min="1" max="12" name="credits" value="<?=e($editing['credits']??3)?>"></div></div><button class="btn btn-primary">Save module</button></form></div></div><?php endif?>
<div class="grid grid-col-2"><div class="card"><div class="card-header">Module catalogue</div><div class="card-body"><table class="table"><thead><tr><th>Code</th><th>Title</th><th>Credits</th><th></th></tr></thead><tbody><?php foreach($modules as $m):?><tr><td><strong><?=e($m['code'])?></strong></td><td><?=e($m['title'])?></td><td><?=$m['credits']?></td><td><a class="action-btn action-edit" href="<?=url('admin/modules.php?action=edit&id='.$m['id'])?>">Edit</a></td></tr><?php endforeach?></tbody></table></div></div>
<div class="card"><div class="card-header">Semester module allocation</div><div class="card-body"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="assign_semester"><div class="form-group"><label>Semester</label><select class="form-control" name="semester_id"><?php foreach($semesters as $s):?><option value="<?=$s['id']?>"><?=e($s['name'].' · '.$s['academic_year'])?></option><?php endforeach?></select></div><label>Select exactly six modules</label><div class="module-check-grid"><?php foreach($modules as $m):?><label class="check-card"><input type="checkbox" name="modules[]" value="<?=$m['id']?>"><span><strong><?=e($m['code'])?></strong><small><?=e($m['title'])?></small></span></label><?php endforeach?></div><button class="btn btn-primary">Assign six modules</button></form></div></div></div>
<?php include __DIR__.'/../includes/footer.php';?>
