<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';require_role('admin');$page_title='Student Allocation - SMIS';
if(is_post()){enforce_csrf();$student=(int)post('student_id');$class=(int)post('class_id');$semester=(int)post('semester_id');db()->beginTransaction();try{db_execute('UPDATE students SET class_id=:class,semester_id=:semester WHERE id=:id',['class'=>$class,'semester'=>$semester,'id'=>$student]);db_execute('DELETE FROM student_modules WHERE student_id=:id',['id'=>$student]);$mods=db_all('SELECT module_id FROM semester_modules WHERE semester_id=:id',['id'=>$semester]);if(count($mods)!==6)throw new RuntimeException('The selected semester must contain exactly six modules.');foreach($mods as $m)db_execute('INSERT INTO student_modules(student_id,module_id,semester_id) VALUES(:student,:module,:semester)',['student'=>$student,'module'=>$m['module_id'],'semester'=>$semester]);foreach(['finance_clearance','registration_clearance','exam_clearance','final_clearance'] as $table)db_execute("INSERT IGNORE INTO $table(student_id) VALUES(:id)",['id'=>$student]);db()->commit();audit_log('allocate','students',(string)$student);respond_success('Student allocated and inherited six semester modules.','admin/students.php');}catch(Throwable $e){db()->rollBack();respond_error($e->getMessage());}}
$students=db_all('SELECT s.id,s.student_number,u.name,u.email,c.name class_name,se.name semester_name,se.academic_year,(SELECT COUNT(*) FROM student_modules sm WHERE sm.student_id=s.id) module_count FROM students s JOIN users u ON u.id=s.user_id LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN semesters se ON se.id=s.semester_id ORDER BY u.name');$classes=db_all('SELECT * FROM classes ORDER BY name');$semesters=db_all('SELECT * FROM semesters ORDER BY starts_on DESC');
include __DIR__.'/../includes/header.php';?>
<div class="page-header"><div><h1>Student Allocation</h1><p>Assign students to classes and automatically inherit the semester's six modules.</p></div><a class="btn btn-primary" href="<?=url('admin/users.php?action=create')?>">Create student account</a></div>
<div class="card"><div class="card-body"><table class="table"><thead><tr><th>Student</th><th>Class</th><th>Semester</th><th>Modules</th><th>Allocate</th></tr></thead><tbody><?php foreach($students as $s):?><tr><td><strong><?=e($s['name'])?></strong><br><small><?=e($s['student_number'])?></small></td><td><?=e($s['class_name']??'Unassigned')?></td><td><?=e(trim(($s['semester_name']??'').' '.($s['academic_year']??''))?:'Unassigned')?></td><td><?=status_badge($s['module_count']==6?'approved':'pending')?> <?=$s['module_count']?> / 6</td><td><form method="post" class="inline-allocation"><?=csrf_field()?><input type="hidden" name="student_id" value="<?=$s['id']?>"><select name="class_id" class="form-control"><?php foreach($classes as $c):?><option value="<?=$c['id']?>"><?=$c['name']?></option><?php endforeach?></select><select name="semester_id" class="form-control"><?php foreach($semesters as $se):?><option value="<?=$se['id']?>"><?=e($se['name'].' '.$se['academic_year'])?></option><?php endforeach?></select><button class="btn btn-sm btn-primary">Assign</button></form></td></tr><?php endforeach?></tbody></table></div></div>
<?php include __DIR__.'/../includes/footer.php';?>
